To - Do Task

4.1


Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

# 1. Initialize an empty array with size 2X2.

In [ ]:
import numpy as np

# 1
empty_array = np.empty((2,2))
print("Empty array of dimension 2x2: \n",empty_array,"\n")


Empty array of dimension 2x2: 
 [[-2.    1.  ]
 [ 1.75 -0.75]] 



2. Initialize an all one array with size 4X2.

In [ ]:
#2
ones_array = np.ones((4,2))
print("All one array with size 4x2: \n",ones_array,"\n")

All one array with size 4x2: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 



3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
#3
full_array = np.full((3,2), 7)
print("Array filled with given value : \n",full_array,"\n")

Array filled with given value : 
 [[7 7]
 [7 7]
 [7 7]] 





```
# This is formatted as code
```

4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
#4
given_array = np.array([[1,2,3,4], [5,6,7,8]])
zeros_array = np.zeros_like(given_array)
print("Zeros array with same shape like given_array: \n",zeros_array,"\n")

Zeros array with same shape like given_array: 
 [[0 0 0 0]
 [0 0 0 0]] 



5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
#5
ones_array = np.ones_like(given_array)
print("Ones array with same shape as given_array: \n",ones_array,"\n")

Ones array with same shape as given_array: 
 [[1 1 1 1]
 [1 1 1 1]] 



6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
#6
new_list=[1,2,3,4]
new_array=np.array(new_list)
print("List: ", new_list);
print("Numpy Array: ", new_array);

List:  [1, 2, 3, 4]
Numpy Array:  [1 2 3 4]


Problem 2

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np
#1
array_in_given_range = np.arange(10,50)
print("Array with values ranging from 10 to 49: \n",array_in_given_range,"\n")

#2
three_by_three_matrix = np.arange(0,9)
reshaped_matrix = three_by_three_matrix.reshape(3,3)
print("Reshaped matrix: \n",reshaped_matrix,"\n")

#3
identity_matrix = np.eye(3)
print("Identity matrix: \n",identity_matrix,"\n")

#4
random_array = np.random.random(30)
mean_of_array = random_array.mean()
print("Mean of random array: ",mean_of_array,"\n")


#5
ten_by_ten_array = np.random.random((10,10))
print("10x10 array: ",ten_by_ten_array, "\n")
max_value = ten_by_ten_array.max()
min_value = ten_by_ten_array.min()
print("Maximum value: ",max_value,"\n")
print("Minimum value: ",min_value,"\n")

#6
zero_array = np.zeros(10)
print("Zero array: \n", zero_array, "\n")
zero_array[4]=1;
print("Zero array after replacing 5th element with 1: \n", zero_array, "\n")


#7
arr = np.array([1,2,0,0,4,0])
print("Original array: \n", arr, "\n")
reversed_arr = arr[::-1]
print("Reversed array: \n", reversed_arr, "\n")


#8
unique_array = np.ones((5,5))
unique_array[1:-1, 1:-1]=0
print("Array with ones on border and zeros elsewhere: \n",unique_array,"\n")


#9
check_board_array = np.zeros((8,8))
check_board_array[0::2, 0::2] = 1
check_board_array[1::2, 1::2] = 1
print("Checkboard pattern: \n",check_board_array, "\n")

Array with values ranging from 10 to 49: 
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49] 

Reshaped matrix: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 

Identity matrix: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

Mean of random array:  0.4710188010480228 

10x10 array:  [[0.04783322 0.29873809 0.90166669 0.93629851 0.53661249 0.4188576
  0.18365087 0.53740921 0.34111682 0.38019999]
 [0.52430632 0.28338527 0.94756981 0.87576134 0.64251924 0.54756898
  0.82350469 0.71391776 0.95866948 0.42277133]
 [0.67627469 0.02068263 0.93353671 0.26173704 0.97943933 0.47071508
  0.90902735 0.98422463 0.98287955 0.39727866]
 [0.51882738 0.77409555 0.77899652 0.48152288 0.77435763 0.14504607
  0.52827213 0.46458931 0.46460348 0.83041965]
 [0.78686045 0.66595158 0.49292093 0.67373594 0.06601549 0.31043371
  0.3812888  0.95826631 0.26295059 0.23570731]
 [0.92720913 0.46982981 0.40105527 0.93424844 0.79879287 0.5244553
  0.64865416 0.10857843 0.

Problem 3

Array Operations:


In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]]);
v = np.array([9,10])
w = np.array([11,12]);

#1
print("Adding array x and y: \n", np.add(x,y),"\n")

#2
print("Subtracting array a and y: \n", np.subtract(x,y), "\n")

#3
print("Multiply array x with 5: \n", np.multiply(x,5), "\n")

#4
print("Squaring each element of array: \n", np.power(x,2), "\n")

#5
print("Dot product of v and w: \n", np.dot(v,w), "\n")
print("Dot product of x and v: \n", np.dot(x,v), "\n")
print("Dot product of x and y: \n", np.dot(x,y), "\n")


#6
concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_col = np.vstack((v, w))
print("\n6. Concatenation:")
print("   x and y along rows:\n", concat_xy_row)
print("   v and w along columns:\n", concat_vw_col)


# 7
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("\n Concatenation of x and v:\n", concat_xv)
except ValueError as e:
    print("\n Error in concatenating x and v:", e)

Adding array x and y: 
 [[ 6  8]
 [10 13]] 

Subtracting array a and y: 
 [[-4 -4]
 [-4 -3]] 

Multiply array x with 5: 
 [[ 5 10]
 [15 25]] 

Squaring each element of array: 
 [[ 1  4]
 [ 9 25]] 

Dot product of v and w: 
 219 

Dot product of x and v: 
 [29 77] 

Dot product of x and y: 
 [[19 22]
 [50 58]] 


6. Concatenation:
   x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
   v and w along columns:
 [[ 9 10]
 [11 12]]

 Error in concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem 4

Matrix Operations:


• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)T = B^TA^T
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [ ]:
import numpy as np
#1
A = np.array([[3,4], [7,8]])
B = np.array([[5,3],[2,1]])

A_inverse = np.linalg.inv(A)
#To prove A.A−1 = I:
result = np.matmul(A,A_inverse)
print("Multiplication of A and inverse of A: \n",result, "\n")


#identity matrix
identity_matrix = np.eye(2)
print("Identity matrix: \n", identity_matrix, "\n")
print("A.A−1 = I: ",np.allclose(result, identity_matrix), "\n")


#2
AB = np.dot(A,B)
print("A.B : \n", AB, "\n")
BA = np.dot(B,A)
print("B.A : \n", BA, "\n")
print("AB == BA ? : ", np.allclose(AB,BA), "\n")

#3
transpose_of_AB = np.transpose(AB)
print("Transpose of AB: \n",transpose_of_AB, "\n")
transpose_of_B = np.transpose(B)
transpose_of_A = np.transpose(A)
A_transpose_b_transpose = np.dot(transpose_of_B, transpose_of_A)
print("Atranspose.Btranspose : \n", A_transpose_b_transpose, "\n")
print(" (AB)T == B^TA^T ?: ", np.allclose(transpose_of_AB, A_transpose_b_transpose), "\n")


#4
# 2x − 3y + z = −1
# x − y + 2z = −3
# x + y − z = 9

a1 = np.array([[2, -3, 1],
              [1, -1, 2],
              [1,  1, -1]])

b1 = np.array([[-1],
              [-3],
              [9]])

a_inverse = np.linalg.inv(a1)
print("Inverse of A: ", a_inverse, "\n")
x = np.dot(a_inverse, b1)
print("Solution X:\n", x)

Multiplication of A and inverse of A: 
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]] 

Identity matrix: 
 [[1. 0.]
 [0. 1.]] 

A.A−1 = I:  True 

A.B : 
 [[23 13]
 [51 29]] 

B.A : 
 [[36 44]
 [13 16]] 

AB == BA ? :  False 

Transpose of AB: 
 [[23 51]
 [13 29]] 

Atranspose.Btranspose : 
 [[23 51]
 [13 29]] 

 (AB)T == B^TA^T ?:  True 

Inverse of A:  [[ 0.11111111  0.22222222  0.55555556]
 [-0.33333333  0.33333333  0.33333333]
 [-0.22222222  0.55555556 -0.11111111]]
Solution X:
 [[ 4.22222222]
 [ 2.33333333]
 [-2.44444444]]


4.2 Experiment: How Fast is Numpy?

1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [ ]:
import time

python_list1=[i for i in range(1,100000)]
python_list2=[j for j in range(1,100000)]

print("Element-wise Addition: \n")
start_at = time.time()
sum1 = [python_list1[i] + python_list2[i] for i in range(len(python_list1))]
end_at = time.time()
print("Time taken using python lists: ", end_at-start_at, "seconds.\n")


array1 = np.arange(1_000_000)
array2 = np.arange(1_000_000)

start_at = time.time()
sum2 = array1 + array2
end_at = time.time()
print("Time taken using NumPy arrays:", end_at - start_at, "seconds")


Time taken using python lists:  0.025566577911376953 seconds.

Time taken using NumPy arrays: 0.004343986511230469 seconds




```
# This is formatted as code
```

2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea-
sure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [ ]:

python_list1=[i for i in range(1,100000)]
python_list2=[j for j in range(1,100000)]

print("Element-wise Multiplicatio: \n")
start_at = time.time()
product1 = [python_list1[i] * python_list2[i] for i in range(len(python_list1))]
end_at = time.time()
print("Time taken using python lists: ", end_at-start_at, "seconds.\n")


array1 = np.arange(1_000_000)
array2 = np.arange(1_000_000)

start_at = time.time()
product2 = array1*array2
end_at = time.time()
print("Time taken using NumPy arrays:", end_at - start_at, "seconds")

Element-wise Multiplication
Time taken using python lists:  0.029119253158569336 seconds.

Time taken using NumPy arrays: 0.0023789405822753906 seconds


3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [ ]:

python_list1=[i for i in range(1,100000)]
python_list2=[j for j in range(1,100000)]

print("Element-wise dot product: \n")
start_at = time.time()
product1 = [python_list1[i] * python_list2[i] for i in range(len(python_list1))]
end_at = time.time()
print("Time taken using python lists: ", end_at-start_at, "seconds.\n")


array1 = np.arange(1_000_000)
array2 = np.arange(1_000_000)

start_at = time.time()
product2 = np.dot(array1, array2)
end_at = time.time()
print("Time taken using NumPy arrays:", end_at - start_at, "seconds")

Element-wise dot product: 

Time taken using python lists:  0.030487775802612305 seconds.

Time taken using NumPy arrays: 0.002006053924560547 seconds


4. Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [ ]:
import time

matrix1 = [[i for i in range(100)] for _ in range(100)]
matrix2 = [[j for j in range(100)] for _ in range(100)]

start_time = time.time()
result_matrix = [[sum(a * b for a, b in zip(row, col)) for col in zip(*matrix2)] for row in matrix1]
end_time = time.time()
print(f"Time taken by Python Lists: {end_time - start_time:.5f} seconds")

# Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.
matrix1_np = np.array(matrix1)
matrix2_np = np.array(matrix2)

start_time = time.time()
result_matrix_np = np.dot(matrix1_np, matrix2_np)
end_time = time.time()
print(f"Time taken by numpy: {end_time - start_time:.5f} seconds")
print("Time taken for matrix multiplication using NumPy arrays:", end_time - start_time, "seconds.")

Time taken by Python Lists: 0.18681 seconds
Time taken by numpy: 0.00150 seconds
Time taken for matrix multiplication using NumPy arrays: 0.0015027523040771484 seconds.
